name: zeroro
description: "A new Flutter project."
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter

  #UI
  cupertino_icons: ^1.0.8
  carousel_slider: ^5.1.1
  syncfusion_flutter_charts: ^29.2.11
  intl: ^0.20.2
  animations: ^2.0.11
  rive: ^0.13.20
  flutter_speed_dial: ^7.0.0
  google_fonts: ^6.2.1
  flutter_3d_controller: ^2.2.0

  #architecture
  flutter_bloc: ^9.1.1
  freezed: ^3.1.0
  freezed_annotation: ^3.1.0
  retrofit: ^4.4.0
  logger: ^2.4.0
  json_annotation: ^4.9.0
  dio: ^5.8.0+1
  injectable:
  get_it:
  shared_preferences: ^2.5.3

  #feature
  go_router: ^14.1.3
  google_sign_in: ^6.2.1
  supabase_flutter: ^2.8.0
  flutter_dotenv: ^5.1.0
  image_picker: ^1.1.2

  #test
  mockito: ^5.4.6

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0
  retrofit_generator: ">=8.0.0 <10.0.0"
  build_runner: ^2.3.3
  json_serializable: ^6.8.0
  injectable_generator:

flutter:
  uses-material-design: true

  assets:
    - .env
    - assets/images/
    - assets/animation/zeroro4.riv
    - assets/zeroro/
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
